analyzer:
  errors:
    # Warnings → Info (делаем менее строгим)
    unused_import: info
    unused_local_variable: info
    dead_code: info
    
    # Info → Ignore (отключаем рекомендации)
    prefer_const_constructors: ignore
    deprecated_member_use: ignore
    use_super_parameters: ignore
    avoid_print: ignore